add some blabla to make shell scripts more friendly

diff --git a/tomcat-6/maven-3.3.9/jdk-8/s2i/bin/assemble b/tomcat-6/maven-3.3.9/jdk-8/s2i/bin/assemble
--- a/tomcat-6/maven-3.3.9/jdk-8/s2i/bin/assemble
+++ b/tomcat-6/maven-3.3.9/jdk-8/s2i/bin/assemble
@@ -7,12 +7,10 @@
 # dependencies from a prior build execution.
 function restore_saved_artifacts() {
   if [ "$(ls -A /opt/s2i/destination/artifacts/ 2>/dev/null)" ]; then
-    echo -n "Restoring saved artifacts from prior build..."
+    echo -n " Restoring saved artifacts from prior build..."
     mv /opt/s2i/destination/artifacts/.m2/repository $HOME/.m2
   fi
 }
-
-env
 
 # Source code provided to S2I is at ${HOME}
 LOCAL_SOURCE_DIR=${HOME}
@@ -36,13 +34,15 @@ chmod -R g+rw $LOCAL_SOURCE_DIR
 if [ -f "$LOCAL_SOURCE_DIR/$POM_PATH/pom.xml" ]; then
 
   if [ -z "$INCREMENTAL" ]; then
-    export INCREMENTAL=false
+    export INCREMENTAL=true
   fi
 
   if [[ "$INCREMENTAL" = "true" ]]; then 
     # restore any maven dependencies which will be present if this is an
     # incremental build
+    echo -n "INCREMENTAL is set to $INCREMENTAL, we are restoring cached workspace containing .m2..."
     restore_saved_artifacts
+    echo " restored"
   fi
 
   pushd $LOCAL_SOURCE_DIR/$POM_PATH &> /dev/null
@@ -71,7 +71,7 @@ if [ -f "$LOCAL_SOURCE_DIR/$POM_PATH/pom.xml" ]; then
   if [ -n "$MAVEN_ARGS_APPEND" ]; then
     export MAVEN_ARGS="$MAVEN_ARGS $MAVEN_ARGS_APPEND"
   fi
-  echo "Found pom.xml... attempting to build with 'mvn ${MAVEN_ARGS}'"
+  echo " Found pom.xml... attempting to build with 'mvn ${MAVEN_ARGS}'"
 
   mvn --version
   mvn $MAVEN_ARGS
@@ -82,25 +82,33 @@ if [ -f "$LOCAL_SOURCE_DIR/$POM_PATH/pom.xml" ]; then
     exit $ERR
   fi
 
-  echo "Cleaning $DEPLOY_DIR..."
+  echo -n "Cleaning $DEPLOY_DIR..."
   rm -rf $DEPLOY_DIR/*
+  echo " cleaned up"
 
-  echo "Moving built war file `find -name $WAR_NAME` into $DEPLOY_DIR for later deployment..."
-
-  mv `find -name $WAR_NAME` $DEPLOY_DIR/ROOT.war
+  if [ ! -z `find -name $WAR_NAME` ]
+  then
+    echo "Moving built war file `find -name $WAR_NAME` into $DEPLOY_DIR for later deployment..."
+    mv `find -name $WAR_NAME` $DEPLOY_DIR/ROOT.war
+  else
+    echo "Aborting due to error : File not found, moving $WAR_NAME file, maybe it doesn't exist"
+    exit 1
+  fi
 
   if [[ "$INCREMENTAL" = "false" ]]; then
-    rm -rf . .m2
+    echo -n "INCREMENTAL is set to $INCREMENTAL, we are now cleaning image \"rm -rf . .m2\"..."
+    rm -rf ./* .m2
+    echo " cleaned up"
   fi
   popd &> /dev/null
 else
   echo "Moving binaries in source directory into $DEPLOY_DIR for later deployment..."
   mv `find -name $WAR_NAME` $DEPLOY_DIR/ROOT.war
   
-ERR=$?
+  ERR=$?
   if [ $ERR -ne 0 ]; then
     echo "Aborting due to error code $ERR from moving $WAR_NAME file, maybe it doesn't exist "
-    exi $ERR
+    exit $ERR
   fi
 fi
 
